from tkinter import *
from PIL import Image, ImageTk
root = Tk()
Grid.rowconfigure(root, 0, weight=1)
Grid.columnconfigure(root, 0, weight=1)
frame=Frame(root)
frame.grid(row=0, column=0, sticky=N+S+E+W)
canvas = Canvas(frame)
img = Image.open('C:/Users/admin/Desktop/瓶盖原始图\\100.jpg')
image = ImageTk.PhotoImage(img)
img_height = image.height()
img_width = image.width()
canvas.grid(row=0, column=0, sticky=NSEW)
canvas.create_image(img_width / 2, img_height / 2, image=image)
root.mainloop()
